 Inicialmente ela falou sobre o Numpy

In [5]:
import numpy as np
import pandas as pd

In [6]:
minhaLista = [0,1,2,3,4,5,6,7,8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
meuArray = np.array(minhaLista)
meuArray



array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


In [10]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
array3 = np.arange(0,10,0.5)
print(array3)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [13]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [19]:
array3 = np.arange(0, 10, 1.5,dtype=int)
array3

array([0, 1, 2, 3, 4, 5, 6])

In [20]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [21]:
type(array4)

numpy.ndarray

In [22]:
array4.dtype

dtype('float64')

In [31]:
vetor1 = np.array([0,1,2,3,4])
print(vetor1)

[0 1 2 3 4]


In [30]:
vetor1[3]


3

In [32]:
vetor1[0:2]

array([0, 1])

In [33]:
vetor1[-1]

4

In [35]:
s = np.array(['Python','Profissional','Java','Água'])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [36]:
s = np.array(['Python',1464321315,'Profissional','Java','Água'])
s

array(['Python', '1464321315', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

In [37]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [38]:
vetor1[0] = 'Novo elemento'

ValueError: ignored

In [39]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])